# Generated by Django 3.0.3 on 2020-05-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200505_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='Image',
            new_name='profilePic',
        ),
    ]
