# Generated by Django 3.0.3 on 2020-05-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20200507_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='postId',
            field=models.CharField(default='240c24018b054e1bbe3fa7c08c580816', max_length=100),
        ),
    ]
