# Generated by Django 3.0.3 on 2020-05-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200507_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='postId',
            field=models.CharField(default='47419322a1d94a58a25e672041d501c8', max_length=100),
        ),
    ]
