# Generated by Django 3.0.3 on 2020-05-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20200507_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='postId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='userId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
