# Generated by Django 3.0.3 on 2020-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='postLikes',
            field=models.IntegerField(default=0),
        ),
    ]
