# Generated by Django 3.0.3 on 2020-05-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20200507_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='postLikedBy',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='likes',
            name='postLikedOf',
            field=models.CharField(default='', max_length=50),
        ),
    ]
