# Generated by Django 3.0.3 on 2020-05-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_allfriends_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='Friends',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='cityName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='companyCity',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='companyDescription',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='companyName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='companyPosition',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='countryName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='coverPic',
            field=models.ImageField(default='media/cover.jpg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='currentEducation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='dOB',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='educationEndYear',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='educationStartYear',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='quote',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='AllFriends',
        ),
        migrations.DeleteModel(
            name='FriendList',
        ),
    ]
