# Generated by Django 3.0.3 on 2020-05-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_auto_20200508_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test1',
            name='field2',
        ),
        migrations.AddField(
            model_name='test',
            name='headline',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='test1',
            name='testField1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
