# Generated by Django 3.0.3 on 2020-05-13 10:09

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_allfriends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='allfriends',
            name='Friends',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=10000, size=None),
        ),
    ]
