# Generated by Django 3.0.3 on 2020-05-08 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20200508_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FriendID', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loggedUser', models.CharField(default='', max_length=100)),
                ('Friends', models.ManyToManyField(to='App.AllFriends')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
    ]
