# Generated by Django 3.0.3 on 2020-05-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_auto_20200508_1453'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
    ]
