# Generated by Django 3.0.3 on 2020-05-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20200508_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='Friends',
            field=models.ManyToManyField(default='', to='App.AllFriends'),
        ),
    ]
