# Generated by Django 3.0.3 on 2020-05-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20200510_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=50)),
                ('Friends', models.TextField()),
            ],
        ),
    ]
