# Generated by Django 3.0.3 on 2020-05-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20200514_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userpost',
            name='userPic',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='Message',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
