# Generated by Django 3.0.3 on 2020-05-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20200515_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
