# Generated by Django 3.0.3 on 2020-05-11 11:14

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20200511_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allfriends',
            name='Friends',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=1000, size=None),
        ),
    ]
