# Generated by Django 3.0.3 on 2020-05-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_auto_20200511_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllFriends',
        ),
    ]
