# Generated by Django 3.0.3 on 2020-05-19 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_auto_20200518_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumID', models.CharField(blank=True, default='', max_length=50)),
                ('Name', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Album', models.CharField(blank=True, default='', max_length=50)),
                ('PhotoID', models.CharField(blank=True, default='', max_length=50)),
                ('Image', models.ImageField(blank=True, upload_to='media')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
