# Generated by Django 3.0.3 on 2020-05-19 15:08

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0024_album_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='postLikedBy',
            field=django_mysql.models.ListCharField(models.CharField(max_length=50), max_length=10000, size=None),
        ),
    ]
