# Generated by Django 3.0.6 on 2020-05-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_auto_20200519_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notificationType',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
