# Generated by Django 3.0.3 on 2020-05-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_auto_20200514_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='userName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
