# Generated by Django 3.0.6 on 2020-05-29 12:18

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_notifications_notificationtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='postId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='likes',
            name='postLikedBy',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=50), max_length=10000, size=None),
        ),
        migrations.AlterField(
            model_name='likes',
            name='postLikedOf',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='likes',
            name='postLikes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
