# Generated by Django 3.0.3 on 2020-05-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_auto_20200514_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
