# Generated by Django 3.0.6 on 2020-05-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_auto_20200529_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='postId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
