# Generated by Django 3.0.6 on 2020-06-02 14:38

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_notifications_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inboxId', models.CharField(blank=True, default='', max_length=50)),
                ('Users', django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=50), max_length=10000, size=None)),
                ('MessageID', models.CharField(blank=True, default='', max_length=500)),
                ('sender', models.CharField(blank=True, default='', max_length=500)),
                ('receiver', models.CharField(blank=True, default='', max_length=500)),
                ('is_read', models.BooleanField(blank=True, default=False)),
                ('Message', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='allfriends',
            name='inboxId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
