# Generated by Django 3.0.3 on 2020-05-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_auto_20200514_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='userPic',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
