# Generated by Django 3.0.6 on 2020-06-04 10:34

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_auto_20200602_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomId', models.CharField(blank=True, default='', max_length=50)),
                ('Users', django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=50), max_length=10000, size=None)),
            ],
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
