# Generated by Django 3.0.6 on 2020-06-10 22:50

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(blank=True, default='', max_length=50)),
                ('messageID', models.CharField(blank=True, default='', max_length=50)),
                ('Message', models.CharField(blank=True, default='', max_length=500)),
                ('sender', models.CharField(blank=True, default='', max_length=500)),
                ('senderName', models.CharField(blank=True, default='', max_length=50)),
                ('senderPic', models.CharField(blank=True, default='', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(blank=True, default='', max_length=50)),
                ('groupName', models.CharField(blank=True, default='', max_length=50)),
                ('Members', django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=50), max_length=10000, size=None)),
                ('groupInfo', models.CharField(blank=True, default='', max_length=50)),
                ('groupPic', models.ImageField(blank=True, default='media/group.jpg', upload_to='media')),
            ],
        ),
        migrations.AddField(
            model_name='userregistration',
            name='Groups',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=50), blank=True, max_length=10000, size=None),
        ),
    ]
