# Generated by Django 3.0.3 on 2020-05-16 19:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='fullName',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='receiver',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sender',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='userId',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='userName',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
