# Generated by Django 3.0.6 on 2020-06-16 15:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_auto_20200610_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allfriends',
            name='inboxId',
        ),
        migrations.AddField(
            model_name='comments',
            name='userInfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.userRegistration'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='joinedDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='album',
            name='AlbumID',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentId',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='Message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='messageID',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='groups',
            name='groupId',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='messages',
            name='MessageID',
            field=models.CharField(blank=True, default='', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='inboxId',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='photos',
            name='PhotoID',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='temproom',
            name='RoomId',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='Message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post',
            field=models.FileField(blank=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='postId',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='dOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='emailAddress',
            field=models.EmailField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='firstName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='lastName',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='userId',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='userName',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.CharField(blank=True, default='', max_length=50)),
                ('commentId', models.CharField(blank=True, default='', max_length=50)),
                ('replyId', models.CharField(blank=True, default='', max_length=50)),
                ('repliedBy', models.CharField(blank=True, default='', max_length=50)),
                ('repliedOn', models.CharField(blank=True, default='', max_length=50)),
                ('reply', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('userInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.userRegistration')),
            ],
        ),
    ]
