# Generated by Django 3.0.3 on 2020-05-17 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_auto_20200517_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='userName',
        ),
    ]
