# Generated by Django 3.0.6 on 2020-06-18 19:02

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_auto_20200616_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='Group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.Groups'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='userInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.userRegistration'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='Users',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=50), default='', max_length=10000, size=None),
        ),
        migrations.AlterField(
            model_name='messages',
            name='inboxId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
