# Generated by Django 3.0.3 on 2020-05-17 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_auto_20200517_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
