# Generated by Django 3.0.6 on 2020-06-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_auto_20200618_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.CharField(default='', max_length=100)),
                ('reportTitle', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='Caption',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='story',
            name='color',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='story',
            name='fontFamily',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='story',
            name='fontSize',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='storyType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
