# Generated by Django 3.0.3 on 2020-05-17 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_requests',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
