# Generated by Django 3.0.6 on 2020-06-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_photos_phototype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='PhotoID',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
