# Generated by Django 3.0.3 on 2020-05-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_friend_requests_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_requests',
            old_name='receiverId',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friend_requests',
            old_name='senderId',
            new_name='sender',
        ),
    ]
