# Generated by Django 3.0.6 on 2020-06-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_remove_photos_phototype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='PostType',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
