# Generated by Django 3.0.3 on 2020-05-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='date',
            new_name='uploadTime',
        ),
    ]
