# Generated by Django 3.0.6 on 2020-06-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_userpost_posttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='AlbumID',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
