# Generated by Django 3.0.3 on 2020-05-17 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_auto_20200518_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='uploadTime',
            field=models.CharField(blank=True, default=datetime.datetime.now, max_length=50),
        ),
    ]
