# Generated by Django 3.0.6 on 2020-07-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_taggedpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='is_online',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
