# Generated by Django 3.0.6 on 2020-07-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_userregistration_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumImageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(blank=True, upload_to='profiles')),
                ('albumId', models.CharField(default='', max_length=200)),
                ('picAlbumId', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='createAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=75)),
                ('albumName', models.CharField(default='', max_length=75)),
                ('albumDescription', models.CharField(default='', max_length=250)),
                ('albumAccessibility', models.CharField(default='', max_length=75)),
                ('albumId', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
