# Generated by Django 3.0.3 on 2020-05-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0044_auto_20200519_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='AlbumID',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='photos',
            name='PhotoID',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
