# Generated by Django 3.0.3 on 2020-05-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_auto_20200519_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='Album',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
