# Generated by Django 3.0.3 on 2020-05-20 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_auto_20200519_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='Album',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
