# Generated by Django 3.0.3 on 2020-05-20 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_userpost_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='Album',
        ),
    ]
