# Generated by Django 3.0.3 on 2020-05-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0050_auto_20200520_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notificationType',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
