# Generated by Django 3.0.3 on 2020-06-01 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0053_notifications_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(default='', max_length=50)),
                ('Friend', models.CharField(blank=True, default='', max_length=50)),
                ('Message', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
