# Generated by Django 3.0.3 on 2020-06-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0054_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='Friend',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='userId',
        ),
        migrations.AddField(
            model_name='allfriends',
            name='roomId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='messages',
            name='MessageID',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='messages',
            name='receiver',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
