# Generated by Django 3.0.3 on 2020-06-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0056_auto_20200602_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomId', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
