# Generated by Django 3.0.3 on 2020-06-02 20:33

from django.db import migrations, models
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0057_temproom'),
    ]

    operations = [
        migrations.AddField(
            model_name='temproom',
            name='Users',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=50), default=django.utils.timezone.now, max_length=10000, size=None),
            preserve_default=False,
        ),
    ]
