# Generated by Django 3.0.3 on 2020-06-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0060_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='commentId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='comments',
            name='commentedBy',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
