# Generated by Django 3.0.3 on 2020-06-06 08:26

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0061_auto_20200605_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupId', models.CharField(blank=True, default='', max_length=50)),
                ('groupName', models.CharField(blank=True, default='', max_length=50)),
                ('Members', django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=50), max_length=10000, size=None)),
                ('sender', models.CharField(blank=True, default='', max_length=500)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
