# Generated by Django 3.0.3 on 2020-06-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0064_auto_20200607_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupchat',
            name='messageID',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
