# Generated by Django 3.0.3 on 2020-06-13 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0072_auto_20200610_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='userInfo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='App.userRegistration'),
        ),
    ]
