# Generated by Django 3.0.3 on 2020-06-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0076_groupchat_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='inboxId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
