# Generated by Django 3.0.3 on 2020-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0079_auto_20200615_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='Caption',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='story',
            name='color',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='story',
            name='fontFamily',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='story',
            name='fontSize',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='story',
            name='storyType',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
