# Generated by Django 3.0.3 on 2020-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0080_auto_20200619_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.CharField(default='', max_length=100)),
                ('reportTitle', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
