# Generated by Django 3.0.3 on 2020-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0081_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='onlineStatus',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
