# Generated by Django 3.0.3 on 2020-06-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0082_userregistration_onlinestatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistration',
            old_name='onlineStatus',
            new_name='is_online',
        ),
    ]
