# Generated by Django 3.0.3 on 2020-06-25 16:45

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0083_auto_20200624_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggedPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taggedId', models.CharField(blank=True, default='', max_length=50)),
                ('taggedPersons', django_mysql.models.ListCharField(models.CharField(blank=True, default='', max_length=50), max_length=10000, size=None)),
                ('postId', models.CharField(blank=True, default='', max_length=50)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
