# Generated by Django 3.0.3 on 2020-06-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0084_taggedpeople'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='PostType',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
