# Generated by Django 3.0.3 on 2020-06-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0086_auto_20200625_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='PhotoID',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
